# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-app-frontend
  template:
    metadata:
      labels:
        app: login-app-frontend
    spec:
      containers:
        - name: frontend
          image: 862848730948.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
          ports:
            - containerPort: 3000
      restartPolicy: Always
---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: login-app-frontend
spec:
  selector:
    app: login-app-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
